[package]
name = "aocutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
num-traits = "0.2.17"
reqwest = { version = "0.11.22", features = ["blocking"] }
