#!/usr/bin/env bash

if [[ -z "$1" || ${#1} != 2 || -z "$2" || ${#2} != 4 ]]; then
    echo "Usage: $0 DD YYYY"
    exit 1
fi

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

day="day$1"
year="year$2"
cd $script_dir/src
rm -rf "$year/$day"
mkdir -p "$year" .
cp -r "./template/dayXX" $year
cp "./template/main.rs" .
find -name "*.rs" -not -path "./template/**" -print0 | xargs -0 sed -i 's/DD/'"$1"'/g'
find -name "*.rs" -not -path "./template/**" -print0 | xargs -0 sed -i 's/YYYY/'"$2"'/g'
