#!/usr/bin/env bash

if [[ -z "$1" || ${#1} != 4 || -z "$2" || ${#2} != 2 ]]; then
    echo "Usage: $0 YYYY DD"
    exit 1
fi

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

year="year$1"
day="day$2"
cd $script_dir/src
rm -rf "$year/$day"
mkdir -p "$year" .
cp -r "./template/dayXX" $year/$day
cp "./template/main.rs" .
echo "pub mod $day;" >> $year/mod.rs
find -name "*.rs" -not -path "./template/**" -print0 | xargs -0 sed -i 's/DD/'"$2"'/g'
find -name "*.rs" -not -path "./template/**" -print0 | xargs -0 sed -i 's/YYYY/'"$1"'/g'
